version: "3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_PASSWORD=password
      - DB_DATABASE=expense_tracker
      - DB_USER=root

  db:
    image: mysql
    environment:
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: expense_tracker
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d

volumes:
  db-data:
